name: gifcurry-ads20000 # you probably want to 'snapcraft register <name>'
version: '2.1.1.0'
summary: Create animated GIFs, optionally overlaid with text, from video files.
description: |
  Create animated GIFs, optionally overlaid with text, from video files.

confinement: devmode # use 'strict' once you have the right plugs and slots

# Using https://github.com/lettier/gifcurry/#ubuntumint

apps:
  gifcurry-gui:
    command: gifcurry_gui
  gifcurry-cli:
    command: gifcurry_cli -?

parts:
  gifcurry:
    plugin: dump
    source: https://github.com/lettier/gifcurry/releases/download/2.1.1.0/gifcurry-linux-2.1.1.0.tar.gz
    after:
      - ffmpeg
    organize:
      gifcurry-linux-2.1.1.0/bin/gifcurry_gui: gifcurry_gui
      gifcurry-linux-2.1.1.0/bin/gifcurry_cli: gifcurry_cli

# This is stolen from https://github.com/phw/peek/blob/master/snapcraft.yaml
# (should be implemented as a remote part really)
  imagemagick:
    plugin: autotools
    source: https://github.com/ImageMagick/ImageMagick.git
    source-type: git
    source-tag: 7.0.7-0
    configflags:
      - --enable-static=no
      - --disable-docs
      - --disable-deprecated
      - --without-autotrace
      - --without-bzlib
      - --without-djvu
      - --without-dps
      - --without-fftw
      - --without-fontconfig
      - --without-fpx
      - --without-freetype
      - --without-gvc
      - --without-jbig
      - --without-jpeg
      - --without-lcms
      - --without-lzma
      - --without-magick-plus-plus
      - --without-openexr
      - --without-openjp2
      - --without-pango
      - --without-png
      - --without-raqm
      - --without-tiff
      - --without-webp
      - --without-wmf
      - --without-x
      - --without-xml
      - --without-zlib
    prime:
      - -bin/ffplay
      - -bin/ffprobe
      - -bin/ffserver
      - -bin/qt-faststart
      - -share/bug
      - -share/doc
      - -share/fonts
      - -share/locale
      - -share/man
    install: |
      sed -i s/avconv/ffmpeg/g $SNAPCRAFT_PART_INSTALL/etc/ImageMagick-7/delegates.xml
